version: 0.1

env:
  secrets-manager:
    # Global
    SLACK_WEBHOOKS: luux-fe:SLACK_WEBHOOKS
    CROSS_ACCOUNT_ROLE: luux-fe:CROSS_ACCOUNT_ROLE
    SLACK_IDS: luux-fe:SLACK_IDS

    # App Url
    VITE_API_URL: luux-fe:API_URL

    VITE_WEB_URLS: luux-fe:ENV_WEB_URLS

    # AWS
    AWS_ACCESS_KEY_ID: luux-fe:AWS_ACCESS_KEY_ID_DEPLOYMENT_FE
    AWS_SECRET_ACCESS_KEY: luux-fe:AWS_SECRET_ACCESS_KEY_DEPLOYMENT_FE
    AWS_S3_WEB_URL: luux-fe:AWS_S3_WEB_APP_PORTAL_URL
    AWS_WEB_CLOUDFRONT_DISTRIBUTION_ID: luux-fe:AWS_APP_PORTAL_CLOUDFRONT_DISTRIBUTION_ID

    # Github
    GITHUB_PAT: luux-fe:GITHUB_PAT

phases:
  install:
    commands:
      # Global

      # App URL
      - echo VITE_API_URL=$VITE_API_URL >> .env
      - echo VITE_WEB_URLS=$VITE_WEB_URLS >> .env

      # AWS
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

      - echo "Current directory $PWD"
      - echo "Initial directory contents (including hidden files):"
      - ls -la

  pre_build:
    commands:
      - npm install -g pnpm@9.10.0
      - pnpm install
      - git config --global url."https://${GITHUB_PAT}@github.com/".insteadOf "https://github.com/"
  build:
    commands:
      # - pnpm audit

      - pnpm build
      - aws s3 sync dist/identity "${AWS_S3_WEB_URL}/identity" --delete
      - aws s3 cp dist/index.html "${AWS_S3_WEB_URL}/index.html"
      - aws cloudfront create-invalidation --distribution-id $AWS_WEB_CLOUDFRONT_DISTRIBUTION_ID --paths '/identity/*' '/index.html'
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      # - bash bin/build-notify.sh $CODEBUILD_BUILD_SUCCEEDING 0 $STAGE $SLACK_WEBHOOKS
